// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: records.proto

package recordspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Records_GetCategoryList_FullMethodName        = "/records.Records/GetCategoryList"
	Records_GetCategoryListForUser_FullMethodName = "/records.Records/GetCategoryListForUser"
	Records_GetRecordById_FullMethodName          = "/records.Records/GetRecordById"
	Records_GetLastGroupForUser_FullMethodName    = "/records.Records/GetLastGroupForUser"
	Records_GetRecords_FullMethodName             = "/records.Records/GetRecords"
	Records_CountRecords_FullMethodName           = "/records.Records/CountRecords"
	Records_GetMultipleRecords_FullMethodName     = "/records.Records/GetMultipleRecords"
)

// RecordsClient is the client API for Records service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordsClient interface {
	GetCategoryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryList, error)
	GetCategoryListForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CategoryList, error)
	GetRecordById(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Record, error)
	GetLastGroupForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*RecordList, error)
	GetRecords(ctx context.Context, in *RecordQuery, opts ...grpc.CallOption) (*RecordList, error)
	CountRecords(ctx context.Context, in *RecordQuery, opts ...grpc.CallOption) (*RecordList, error)
	GetMultipleRecords(ctx context.Context, in *MultiRecordQuery, opts ...grpc.CallOption) (*MultiRecordAnswer, error)
}

type recordsClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordsClient(cc grpc.ClientConnInterface) RecordsClient {
	return &recordsClient{cc}
}

func (c *recordsClient) GetCategoryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryList)
	err := c.cc.Invoke(ctx, Records_GetCategoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) GetCategoryListForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CategoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryList)
	err := c.cc.Invoke(ctx, Records_GetCategoryListForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) GetRecordById(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_GetRecordById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) GetLastGroupForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, Records_GetLastGroupForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) GetRecords(ctx context.Context, in *RecordQuery, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, Records_GetRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) CountRecords(ctx context.Context, in *RecordQuery, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, Records_CountRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) GetMultipleRecords(ctx context.Context, in *MultiRecordQuery, opts ...grpc.CallOption) (*MultiRecordAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiRecordAnswer)
	err := c.cc.Invoke(ctx, Records_GetMultipleRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordsServer is the server API for Records service.
// All implementations must embed UnimplementedRecordsServer
// for forward compatibility.
type RecordsServer interface {
	GetCategoryList(context.Context, *Empty) (*CategoryList, error)
	GetCategoryListForUser(context.Context, *User) (*CategoryList, error)
	GetRecordById(context.Context, *RecordRequest) (*Record, error)
	GetLastGroupForUser(context.Context, *User) (*RecordList, error)
	GetRecords(context.Context, *RecordQuery) (*RecordList, error)
	CountRecords(context.Context, *RecordQuery) (*RecordList, error)
	GetMultipleRecords(context.Context, *MultiRecordQuery) (*MultiRecordAnswer, error)
	mustEmbedUnimplementedRecordsServer()
}

// UnimplementedRecordsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordsServer struct{}

func (UnimplementedRecordsServer) GetCategoryList(context.Context, *Empty) (*CategoryList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryList not implemented")
}
func (UnimplementedRecordsServer) GetCategoryListForUser(context.Context, *User) (*CategoryList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryListForUser not implemented")
}
func (UnimplementedRecordsServer) GetRecordById(context.Context, *RecordRequest) (*Record, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecordById not implemented")
}
func (UnimplementedRecordsServer) GetLastGroupForUser(context.Context, *User) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastGroupForUser not implemented")
}
func (UnimplementedRecordsServer) GetRecords(context.Context, *RecordQuery) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecords not implemented")
}
func (UnimplementedRecordsServer) CountRecords(context.Context, *RecordQuery) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method CountRecords not implemented")
}
func (UnimplementedRecordsServer) GetMultipleRecords(context.Context, *MultiRecordQuery) (*MultiRecordAnswer, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMultipleRecords not implemented")
}
func (UnimplementedRecordsServer) mustEmbedUnimplementedRecordsServer() {}
func (UnimplementedRecordsServer) testEmbeddedByValue()                 {}

// UnsafeRecordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordsServer will
// result in compilation errors.
type UnsafeRecordsServer interface {
	mustEmbedUnimplementedRecordsServer()
}

func RegisterRecordsServer(s grpc.ServiceRegistrar, srv RecordsServer) {
	// If the following call panics, it indicates UnimplementedRecordsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Records_ServiceDesc, srv)
}

func _Records_GetCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetCategoryList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_GetCategoryListForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetCategoryListForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetCategoryListForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetCategoryListForUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_GetRecordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetRecordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetRecordById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetRecordById(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_GetLastGroupForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetLastGroupForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetLastGroupForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetLastGroupForUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetRecords(ctx, req.(*RecordQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_CountRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).CountRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_CountRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).CountRecords(ctx, req.(*RecordQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_GetMultipleRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiRecordQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetMultipleRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetMultipleRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetMultipleRecords(ctx, req.(*MultiRecordQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Records_ServiceDesc is the grpc.ServiceDesc for Records service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Records_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "records.Records",
	HandlerType: (*RecordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategoryList",
			Handler:    _Records_GetCategoryList_Handler,
		},
		{
			MethodName: "GetCategoryListForUser",
			Handler:    _Records_GetCategoryListForUser_Handler,
		},
		{
			MethodName: "GetRecordById",
			Handler:    _Records_GetRecordById_Handler,
		},
		{
			MethodName: "GetLastGroupForUser",
			Handler:    _Records_GetLastGroupForUser_Handler,
		},
		{
			MethodName: "GetRecords",
			Handler:    _Records_GetRecords_Handler,
		},
		{
			MethodName: "CountRecords",
			Handler:    _Records_CountRecords_Handler,
		},
		{
			MethodName: "GetMultipleRecords",
			Handler:    _Records_GetMultipleRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "records.proto",
}
