// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: records.proto

package recordspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{2}
}

func (x *RecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryList) Reset() {
	*x = CategoryList{}
	mi := &file_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryList) ProtoMessage() {}

func (x *CategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryList.ProtoReflect.Descriptor instead.
func (*CategoryList) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryList) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Category struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Unit                  *string                `protobuf:"bytes,4,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	Type                  *string                `protobuf:"bytes,5,opt,name=type,proto3,oneof" json:"type,omitempty"`
	DefaultRepresentation *string                `protobuf:"bytes,6,opt,name=default_representation,json=defaultRepresentation,proto3,oneof" json:"default_representation,omitempty"`
	IsLegacy              *bool                  `protobuf:"varint,7,opt,name=is_legacy,json=isLegacy,proto3,oneof" json:"is_legacy,omitempty"`
	Subcategory           *string                `protobuf:"bytes,8,opt,name=subcategory,proto3,oneof" json:"subcategory,omitempty"`
	DoctorCanAdd          *bool                  `protobuf:"varint,9,opt,name=doctor_can_add,json=doctorCanAdd,proto3,oneof" json:"doctor_can_add,omitempty"`
	DoctorCanReplace      *bool                  `protobuf:"varint,10,opt,name=doctor_can_replace,json=doctorCanReplace,proto3,oneof" json:"doctor_can_replace,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Category) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *Category) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Category) GetDefaultRepresentation() string {
	if x != nil && x.DefaultRepresentation != nil {
		return *x.DefaultRepresentation
	}
	return ""
}

func (x *Category) GetIsLegacy() bool {
	if x != nil && x.IsLegacy != nil {
		return *x.IsLegacy
	}
	return false
}

func (x *Category) GetSubcategory() string {
	if x != nil && x.Subcategory != nil {
		return *x.Subcategory
	}
	return ""
}

func (x *Category) GetDoctorCanAdd() bool {
	if x != nil && x.DoctorCanAdd != nil {
		return *x.DoctorCanAdd
	}
	return false
}

func (x *Category) GetDoctorCanReplace() bool {
	if x != nil && x.DoctorCanReplace != nil {
		return *x.DoctorCanReplace
	}
	return false
}

type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{5}
}

func (x *RecordList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RecordList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecordSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSource) Reset() {
	*x = RecordSource{}
	mi := &file_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSource) ProtoMessage() {}

func (x *RecordSource) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSource.ProtoReflect.Descriptor instead.
func (*RecordSource) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{6}
}

func (x *RecordSource) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RecordSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RecordFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFile) Reset() {
	*x = RecordFile{}
	mi := &file_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFile) ProtoMessage() {}

func (x *RecordFile) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFile.ProtoReflect.Descriptor instead.
func (*RecordFile) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{7}
}

func (x *RecordFile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecordFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecordFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Additions     string                 `protobuf:"bytes,8,opt,name=additions,proto3" json:"additions,omitempty"`
	Group         string                 `protobuf:"bytes,9,opt,name=group,proto3" json:"group,omitempty"`
	Source        *RecordSource          `protobuf:"bytes,10,opt,name=source,proto3,oneof" json:"source,omitempty"`
	AttachedFiles []*RecordFile          `protobuf:"bytes,11,rep,name=attached_files,json=attachedFiles,proto3" json:"attached_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_records_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{8}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Record) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Record) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Record) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Record) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Record) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Record) GetAdditions() string {
	if x != nil {
		return x.Additions
	}
	return ""
}

func (x *Record) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Record) GetSource() *RecordSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Record) GetAttachedFiles() []*RecordFile {
	if x != nil {
		return x.AttachedFiles
	}
	return nil
}

type RecordQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryIds   []int64                `protobuf:"varint,1,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	FromTimestamp *int64                 `protobuf:"varint,2,opt,name=from_timestamp,json=fromTimestamp,proto3,oneof" json:"from_timestamp,omitempty"`
	ToTimestamp   *int64                 `protobuf:"varint,3,opt,name=to_timestamp,json=toTimestamp,proto3,oneof" json:"to_timestamp,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Limit         *int64                 `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	UserId        int32                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WithGroup     bool                   `protobuf:"varint,7,opt,name=with_group,json=withGroup,proto3" json:"with_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordQuery) Reset() {
	*x = RecordQuery{}
	mi := &file_records_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordQuery) ProtoMessage() {}

func (x *RecordQuery) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordQuery.ProtoReflect.Descriptor instead.
func (*RecordQuery) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{9}
}

func (x *RecordQuery) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *RecordQuery) GetFromTimestamp() int64 {
	if x != nil && x.FromTimestamp != nil {
		return *x.FromTimestamp
	}
	return 0
}

func (x *RecordQuery) GetToTimestamp() int64 {
	if x != nil && x.ToTimestamp != nil {
		return *x.ToTimestamp
	}
	return 0
}

func (x *RecordQuery) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *RecordQuery) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *RecordQuery) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordQuery) GetWithGroup() bool {
	if x != nil {
		return x.WithGroup
	}
	return false
}

type MultiRecordQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*RecordQuery         `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRecordQuery) Reset() {
	*x = MultiRecordQuery{}
	mi := &file_records_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRecordQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRecordQuery) ProtoMessage() {}

func (x *MultiRecordQuery) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRecordQuery.ProtoReflect.Descriptor instead.
func (*MultiRecordQuery) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{10}
}

func (x *MultiRecordQuery) GetQueries() []*RecordQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type MultiRecordAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*RecordList          `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRecordAnswer) Reset() {
	*x = MultiRecordAnswer{}
	mi := &file_records_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRecordAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRecordAnswer) ProtoMessage() {}

func (x *MultiRecordAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_records_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRecordAnswer.ProtoReflect.Descriptor instead.
func (*MultiRecordAnswer) Descriptor() ([]byte, []int) {
	return file_records_proto_rawDescGZIP(), []int{11}
}

func (x *MultiRecordAnswer) GetAnswers() []*RecordList {
	if x != nil {
		return x.Answers
	}
	return nil
}

var File_records_proto protoreflect.FileDescriptor

const file_records_proto_rawDesc = "" +
	"\n" +
	"\rrecords.proto\x12\arecords\"\a\n" +
	"\x05Empty\"\x16\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1f\n" +
	"\rRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\fCategoryList\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.records.CategoryR\n" +
	"categories\"\xef\x03\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04unit\x18\x04 \x01(\tH\x01R\x04unit\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x05 \x01(\tH\x02R\x04type\x88\x01\x01\x12:\n" +
	"\x16default_representation\x18\x06 \x01(\tH\x03R\x15defaultRepresentation\x88\x01\x01\x12 \n" +
	"\tis_legacy\x18\a \x01(\bH\x04R\bisLegacy\x88\x01\x01\x12%\n" +
	"\vsubcategory\x18\b \x01(\tH\x05R\vsubcategory\x88\x01\x01\x12)\n" +
	"\x0edoctor_can_add\x18\t \x01(\bH\x06R\fdoctorCanAdd\x88\x01\x01\x121\n" +
	"\x12doctor_can_replace\x18\n" +
	" \x01(\bH\aR\x10doctorCanReplace\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_unitB\a\n" +
	"\x05_typeB\x19\n" +
	"\x17_default_representationB\f\n" +
	"\n" +
	"_is_legacyB\x0e\n" +
	"\f_subcategoryB\x11\n" +
	"\x0f_doctor_can_addB\x15\n" +
	"\x13_doctor_can_replace\"M\n" +
	"\n" +
	"RecordList\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.records.RecordR\arecords\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\">\n" +
	"\fRecordSource\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\x05\n" +
	"\x03_id\"D\n" +
	"\n" +
	"RecordFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xed\x02\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12\x1c\n" +
	"\tadditions\x18\b \x01(\tR\tadditions\x12\x14\n" +
	"\x05group\x18\t \x01(\tR\x05group\x122\n" +
	"\x06source\x18\n" +
	" \x01(\v2\x15.records.RecordSourceH\x00R\x06source\x88\x01\x01\x12:\n" +
	"\x0eattached_files\x18\v \x03(\v2\x13.records.RecordFileR\rattachedFilesB\t\n" +
	"\a_source\"\xad\x02\n" +
	"\vRecordQuery\x12!\n" +
	"\fcategory_ids\x18\x01 \x03(\x03R\vcategoryIds\x12*\n" +
	"\x0efrom_timestamp\x18\x02 \x01(\x03H\x00R\rfromTimestamp\x88\x01\x01\x12&\n" +
	"\fto_timestamp\x18\x03 \x01(\x03H\x01R\vtoTimestamp\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x03H\x02R\x06offset\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\x03H\x03R\x05limit\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"with_group\x18\a \x01(\bR\twithGroupB\x11\n" +
	"\x0f_from_timestampB\x0f\n" +
	"\r_to_timestampB\t\n" +
	"\a_offsetB\b\n" +
	"\x06_limit\"B\n" +
	"\x10MultiRecordQuery\x12.\n" +
	"\aqueries\x18\x01 \x03(\v2\x14.records.RecordQueryR\aqueries\"B\n" +
	"\x11MultiRecordAnswer\x12-\n" +
	"\aanswers\x18\x01 \x03(\v2\x13.records.RecordListR\aanswers2\xc7\x03\n" +
	"\aRecords\x12:\n" +
	"\x0fGetCategoryList\x12\x0e.records.Empty\x1a\x15.records.CategoryList\"\x00\x12@\n" +
	"\x16GetCategoryListForUser\x12\r.records.User\x1a\x15.records.CategoryList\"\x00\x12:\n" +
	"\rGetRecordById\x12\x16.records.RecordRequest\x1a\x0f.records.Record\"\x00\x12;\n" +
	"\x13GetLastGroupForUser\x12\r.records.User\x1a\x13.records.RecordList\"\x00\x129\n" +
	"\n" +
	"GetRecords\x12\x14.records.RecordQuery\x1a\x13.records.RecordList\"\x00\x12;\n" +
	"\fCountRecords\x12\x14.records.RecordQuery\x1a\x13.records.RecordList\"\x00\x12M\n" +
	"\x12GetMultipleRecords\x12\x19.records.MultiRecordQuery\x1a\x1a.records.MultiRecordAnswer\"\x00B<Z:github.com/tikhonp/maigo/internal/grpc/recordspb;recordspbb\x06proto3"

var (
	file_records_proto_rawDescOnce sync.Once
	file_records_proto_rawDescData []byte
)

func file_records_proto_rawDescGZIP() []byte {
	file_records_proto_rawDescOnce.Do(func() {
		file_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_records_proto_rawDesc), len(file_records_proto_rawDesc)))
	})
	return file_records_proto_rawDescData
}

var file_records_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_records_proto_goTypes = []any{
	(*Empty)(nil),             // 0: records.Empty
	(*User)(nil),              // 1: records.User
	(*RecordRequest)(nil),     // 2: records.RecordRequest
	(*CategoryList)(nil),      // 3: records.CategoryList
	(*Category)(nil),          // 4: records.Category
	(*RecordList)(nil),        // 5: records.RecordList
	(*RecordSource)(nil),      // 6: records.RecordSource
	(*RecordFile)(nil),        // 7: records.RecordFile
	(*Record)(nil),            // 8: records.Record
	(*RecordQuery)(nil),       // 9: records.RecordQuery
	(*MultiRecordQuery)(nil),  // 10: records.MultiRecordQuery
	(*MultiRecordAnswer)(nil), // 11: records.MultiRecordAnswer
}
var file_records_proto_depIdxs = []int32{
	4,  // 0: records.CategoryList.categories:type_name -> records.Category
	8,  // 1: records.RecordList.records:type_name -> records.Record
	6,  // 2: records.Record.source:type_name -> records.RecordSource
	7,  // 3: records.Record.attached_files:type_name -> records.RecordFile
	9,  // 4: records.MultiRecordQuery.queries:type_name -> records.RecordQuery
	5,  // 5: records.MultiRecordAnswer.answers:type_name -> records.RecordList
	0,  // 6: records.Records.GetCategoryList:input_type -> records.Empty
	1,  // 7: records.Records.GetCategoryListForUser:input_type -> records.User
	2,  // 8: records.Records.GetRecordById:input_type -> records.RecordRequest
	1,  // 9: records.Records.GetLastGroupForUser:input_type -> records.User
	9,  // 10: records.Records.GetRecords:input_type -> records.RecordQuery
	9,  // 11: records.Records.CountRecords:input_type -> records.RecordQuery
	10, // 12: records.Records.GetMultipleRecords:input_type -> records.MultiRecordQuery
	3,  // 13: records.Records.GetCategoryList:output_type -> records.CategoryList
	3,  // 14: records.Records.GetCategoryListForUser:output_type -> records.CategoryList
	8,  // 15: records.Records.GetRecordById:output_type -> records.Record
	5,  // 16: records.Records.GetLastGroupForUser:output_type -> records.RecordList
	5,  // 17: records.Records.GetRecords:output_type -> records.RecordList
	5,  // 18: records.Records.CountRecords:output_type -> records.RecordList
	11, // 19: records.Records.GetMultipleRecords:output_type -> records.MultiRecordAnswer
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_records_proto_init() }
func file_records_proto_init() {
	if File_records_proto != nil {
		return
	}
	file_records_proto_msgTypes[4].OneofWrappers = []any{}
	file_records_proto_msgTypes[6].OneofWrappers = []any{}
	file_records_proto_msgTypes[8].OneofWrappers = []any{}
	file_records_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_records_proto_rawDesc), len(file_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_records_proto_goTypes,
		DependencyIndexes: file_records_proto_depIdxs,
		MessageInfos:      file_records_proto_msgTypes,
	}.Build()
	File_records_proto = out.File
	file_records_proto_goTypes = nil
	file_records_proto_depIdxs = nil
}
